[package]
name = "dogmv"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.10"
webkit6 = "0.5"
comrak = "0.24"
syntect = "5.2"
notify = "6.1"
log = "0.4"
env_logger = "0.11"
thiserror = "1.0"
ctor = "0.2"
